apiVersion: v1
kind: Pod
metadata:
  name: with-limits
  labels:
    name: with-limits
spec:
  containers:
  - name: with-limits
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
